version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-fpm-node-browsers
      - image: circleci/postgres:alpine
        environment:
        - POSTGRES_USER: default
        - POSTGRES_DB: default
        - POSTGRES_PASSWORD: secret
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt install -y postgresql-client
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install pgsql
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: php artisan migrate --env=testing --force
      - run:
         name: Test 1 - Run Phpunit for Server-Side HTTP Requests & PHP Unit Testing
         command: .vendor/bin/phpunit
